import type { Metadata } from "next";
import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from "./navbar";
import Container from 'react-bootstrap/Container';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dakota's FCC Projects",
  description: "Generated by create next app",
};

const brand = {
  title: "Dakota's FCC Projects",
  icon: "/fcc.png",
  alt: "freeCodeCamp Logo"
};

const links = [
  { name: "25/5 Timer", href: "/clock", icon: "timer" },
  { name: "Calculator", href: "/calculator", icon: "calculate" },
  { name: "Drums", href: "/drums", icon: "music_note" },
  { name: "Markdown Previewer", href: "/markdown", icon: "markdown" },
  { name: "Advice Machine", href: "/advice", icon: "format_quote" },
];

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`h-screen flex flex-row flex-wrap ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar appBrand={brand} appLinks={links} />
        <Container fluid={true} className="size-full flex flex-col place-content-center place-items-center text-center">
        {children}
        </Container>
      </body>
    </html>
  );
}
